modLoader="javafml"
loaderVersion="[31,)"
license="GNU General Public License v3.0"

[[mods]]
    modId="cspirit"
    namespace="cspirit"
    version="1.0.0"
    displayName="Christmas Spirit"
    authors="Calemi, CaptainKray, Kryto627"
    description='''
    ♫ Deck the mines with boughs of holly! ♫

    Wrap presents, eat holiday sweets, and decorate your Minecraft world with Christmas-themed features!
    And...who knows? You might even get to see Santa...
    '''

[[dependencies.cspirit]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"